### ISSUE TITLE
Exposing BigQuery "quiet" parameter in FinnGenUtilsR calls

### ISSUE THREAD

**Issue by siirtola** [FINNGEN/FinnGenUtilsR#5]
This would allow to silence the BQ  in production, and the logs would be cleaner. The default could be FALSE so no code would break.

**Comment by javier-gracia-tabuenca-tuni** [comment]
closed by #6 

now fg_bq_append_xxx functions pass extra parameters to bq_project_query, (e.g allows to pass quiet=TRUE)
